name: Build Angular 9 App (Dev)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (Dev mode)
        run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
